Code for development and testing of the function log_cosh

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np
import torch

from janelia_core.ml.extra_torch_functions import log_cosh

In [3]:
x = torch.randn([10, 2])

In [10]:
y_test = log_cosh(x).numpy()
y_true = np.log(np.cosh(x.numpy()))

In [12]:
np.abs(y_test - y_true)/np.abs(y_true)

array([[2.0812538e-06, 9.5687824e-07],
       [5.1708668e-07, 3.4527602e-07],
       [0.0000000e+00, 6.9699595e-08],
       [9.3711300e-08, 1.9602226e-07],
       [1.1108871e-07, 2.7610909e-07],
       [0.0000000e+00, 7.1023857e-07],
       [1.1912549e-07, 0.0000000e+00],
       [1.0456555e-07, 1.8340631e-06],
       [0.0000000e+00, 7.6557200e-08],
       [4.4100966e-07, 0.0000000e+00]], dtype=float32)

In [13]:
y_test

array([[0.01029205, 0.04671809],
       [0.05043066, 0.03236794],
       [0.86679727, 0.21379124],
       [1.272091  , 0.11402658],
       [0.13413751, 0.16190511],
       [1.1916792 , 0.02360308],
       [0.12508795, 0.6067208 ],
       [0.28501087, 0.03249863],
       [1.675906  , 1.557127  ],
       [0.06757745, 1.016578  ]], dtype=float32)

In [14]:
y_true

array([[0.01029207, 0.04671805],
       [0.05043068, 0.03236793],
       [0.86679727, 0.21379122],
       [1.2720909 , 0.11402655],
       [0.1341375 , 0.16190515],
       [1.1916792 , 0.02360306],
       [0.12508793, 0.6067208 ],
       [0.2850109 , 0.03249869],
       [1.675906  , 1.5571271 ],
       [0.06757748, 1.016578  ]], dtype=float32)