In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from pathlib import Path

import h5py
import numpy as np

from janelia_core.utils.data_saving import load_structured_hdf5
from janelia_core.utils.data_saving import save_structured_hdf5

## Parameters go here

In [7]:
save_file = r'/Users/bishopw/Desktop/data.h5'

#data = np.asarray([[0, 1, 2], [3, 4, 5]])
data = {0: np.asarray([[0, 1, 2], [3, 4, 5]]), 
        1: [2*np.asarray([[0, 1, 2], [3, 4, 5]]), np.asarray([0, 1, 2])], 
        2: [np.asarray([i]) for i in range(23)],
        3: [np.asarray([0]), {'k0': [np.asarray([2]), np.asarray([3.3])]}]}

## Save the data here

In [9]:
save_structured_hdf5(o = data, f=Path(save_file), name='data', overwrite=True)

## Load the data here

In [18]:
data = load_structured_hdf5(f=Path(save_file))

In [19]:
data

{0: array([[0, 1, 2],
        [3, 4, 5]]),
 1: [array([[ 0,  2,  4],
         [ 6,  8, 10]]),
  array([0, 1, 2])],
 2: [array([0]),
  array([1]),
  array([2]),
  array([3]),
  array([4]),
  array([5]),
  array([6]),
  array([7]),
  array([8]),
  array([9]),
  array([10]),
  array([11]),
  array([12]),
  array([13]),
  array([14]),
  array([15]),
  array([16]),
  array([17]),
  array([18]),
  array([19]),
  array([20]),
  array([21]),
  array([22])],
 3: [array([0]), {'k0': [array([2]), array([3.3])]}]}