Code to develop and test MultiParamCMap objects

In [1]:
%load_ext autoreload
%autoreload 2

In [6]:
import numpy as np

from janelia_core.visualization.custom_color_maps import MultiParamCMap

## Parameters go here

In [7]:
param_vl_ranges = [(2, 4, .5), (3, 3.5, .1)]

## Test code goes here

In [135]:
param_vls = [np.arange(*r) for r in param_vl_ranges]
n_param_vls = [len(vls) for vls in param_vls]
clrs = np.zeros([*n_param_vls, 3])
for i_0 in range(n_param_vls[0]):
    for i_1 in range(n_param_vls[1]):
        clrs[i_0, i_1, :] = param_vls[0][i_0]*100 + param_vls[1][i_1]
        
        
for i in range(3):
    clrs[:,:,i] = (10**i)*clrs[:,:, i]
        
cmap = MultiParamCMap(param_vl_ranges=param_vl_ranges, clrs=clrs)

In [136]:
vls_0 = np.asarray([[2, 3, 3.5], [2, 3, 2.1]])
vls_1 = np.asarray([[3, 3.1, 3.3], [3.1, 3.1, 3.5]])


In [137]:
vls_0

array([[2. , 3. , 3.5],
       [2. , 3. , 2.1]])

In [138]:
vls_1

array([[3. , 3.1, 3.3],
       [3.1, 3.1, 3.5]])

In [139]:
capped_vls = cmap[vls_0, vls_1]

In [140]:
capped_vls[:, :, 0]

array([[203. , 303.1, 353.3],
       [203.1, 303.1, 203.4]])

In [141]:
capped_vls[:, :, 1]

array([[2030., 3031., 3533.],
       [2031., 3031., 2034.]])

In [142]:
capped_vls[:, :, 2]

array([[20300., 30310., 35330.],
       [20310., 30310., 20340.]])

In [143]:
from matplotlib import cm

In [144]:

viridis = cm.get_cmap('viridis', 12)

In [145]:
type(viridis)

matplotlib.colors.ListedColormap