In [1]:
%load_ext autoreload
%autoreload 2

from dipy.align.imaffine import AffineMap

from janelia_core.registration.registration import get_reg_image_data
from janelia_core.registration.registration import apply_2d_dipy_affine_transform


In [2]:
import numpy as np

In [28]:
affine = np.eye(3)
affine[0,2] = 1
affine[1,2] = -2
t = AffineMap(affine)

In [31]:
row = np.asarray([1,2,3,4,5])
orig_im = np.asarray([row, row, row, row, row])
orig_im = np.stack([orig_im, orig_im])
reg_img = apply_2d_dipy_affine_transform(orig_im, t)


reg_slice = (slice(0,2,1), slice(0,4,1), slice(2,5,1))
reg_img_slice = get_reg_image_data(orig_im, [2,5,5], t, reg_slice)

In [32]:
orig_im

array([[[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]],

       [[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]]])

In [33]:
reg_img

array([[[0., 0., 1., 2., 3.],
        [0., 0., 1., 2., 3.],
        [0., 0., 1., 2., 3.],
        [0., 0., 1., 2., 3.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 1., 2., 3.],
        [0., 0., 1., 2., 3.],
        [0., 0., 1., 2., 3.],
        [0., 0., 1., 2., 3.],
        [0., 0., 0., 0., 0.]]])

In [34]:
reg_img_slice

array([[[1., 2., 3.],
        [1., 2., 3.],
        [1., 2., 3.],
        [1., 2., 3.]],

       [[1., 2., 3.],
        [1., 2., 3.],
        [1., 2., 3.],
        [1., 2., 3.]]])