In [8]:
import torch
import numpy as np

In [2]:
x = torch.ones(1)
x.requires_grad = True

In [3]:
y = x**2

In [4]:
z = x**3

In [5]:
y.backward()
z.backward()

In [6]:
x.grad

tensor([5.])

In [15]:
m1 = torch.from_numpy(np.asarray([[1, 2], [3, 4]]))
m2 = torch.from_numpy(np.asarray([[5, 6], [7, 8]]))

In [17]:
torch.mul(m1, m2)

tensor([[ 5, 12],
        [21, 32]], dtype=torch.int32)

In [18]:
m1

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [19]:
m2

tensor([[5, 6],
        [7, 8]], dtype=torch.int32)

In [22]:
(m1*m2).sum()

tensor(70)